### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by mxmilkiib** [kovetskiy/sxhkd-vim#1]
It appears there are a few things not covered atm?

![rose_2019-11-12-09:24:34](https://user-images.githubusercontent.com/108225/68658977-5ae7da00-052e-11ea-9180-b526399b67d9.png)

**Comment by kovetskiy** [comment]
Hi. sxhkd-vim matches sxhkdrc syntax and links with your theme, make sure that your vim colorscheme covers Comment, Identifier, Conditional, Constant and Macro hl groups.

https://github.com/kovetskiy/sxhkd-vim/blob/master/syntax/sxhkd.vim#L13-L17

**Comment by mxmilkiib** [comment]
Ah, it turns out the lines without syntax highlighting start with double spaces, not tabs.
