### ISSUE TITLE
Comments break indenting

### ISSUE THREAD

**Issue by ettom** [kovetskiy/sxhkd-vim#2]
When doing `gg=G`
```
# comment
super + Return
        $TERMINAL
```
turns into
```
# comment
        super + Return
$TERMINAL
```
Minimal vimrc:
```
set nocompatible
let &runtimepath  = '~/.vim/bundle/sxhkd-vim,' . &runtimepath
filetype plugin indent on
syntax enable
```

**Comment by kovetskiy** [comment]
![sxhkd-fix](https://user-images.githubusercontent.com/8445924/70836295-cb756580-1e10-11ea-9406-d811e79b80fc.gif)


hi, it should be fixed now, please check and let me know if I can close the issue

**Comment by ettom** [comment]
Works great, thanks!
